### PR TITLE
 jaeger 1.21.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Thanks for getting this started! The `go` packaging landscape has settled down some, and will hopefully be more predictable going forward. This adapts some of the best practices from other feedstocks, and seems to work! **Definitely*** still a work in progress, but builds locally on linux, so figured it was worth a shot on CI to find more issues.

Notes:
- adds self as maintainer :wave:
- **definitely** need to adapt the approach from other `go` things to automate the license compliance with `go-licenses`
- considering adding multiple outputs, one for each of the different binaries... the final size is 107MB, which seems pretty large, but a given use case might just need one or two of them, so basically:
  - `jaeger` depends on all of...
    - `jaeger-all-in-one`
    - `jaeger-agent`
    - ...

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
License thing is a no-go... still working on splitting outputs.

**Comment by goanpeca** [comment]
LGTM @bollwyvl, let me know when it is ready :)

**Comment by bollwyvl** [comment]
Had another go (:rofl:) at the licenses, but still can't figure out why it can't find anything. Broken up, the package sizes are much more reasonable:

```
 9.4M Feb 15 21:00 build_artifacts/linux-64/jaeger-agent-1.21.0-ha770c72_0.tar.bz2
  21M Feb 15 21:00 build_artifacts/linux-64/jaeger-all-in-one-1.21.0-ha770c72_0.tar.bz2
  16M Feb 15 21:00 build_artifacts/linux-64/jaeger-collector-1.21.0-ha770c72_0.tar.bz2
 7.9M Feb 15 21:00 build_artifacts/linux-64/jaeger-example-hotrod-1.21.0-ha770c72_0.tar.bz2
  14M Feb 15 21:01 build_artifacts/linux-64/jaeger-ingester-1.21.0-ha770c72_0.tar.bz2
  19M Feb 15 21:01 build_artifacts/linux-64/jaeger-query-1.21.0-ha770c72_0.tar.bz2
 5.3M Feb 15 21:01 build_artifacts/linux-64/jaeger-tracegen-1.21.0-ha770c72_0.tar.bz2
 9.4K Feb 15 21:01 build_artifacts/linux-64/jaeger-1.21.0-ha770c72_0.tar.bz2
```

**Comment by bollwyvl** [comment]
If CI comes up clean, no further changes planned.

**Comment by bollwyvl** [comment]
:tada: :heavy_check_mark:

**Pull request merged**
